### ISSUE TITLE
Introduction should clarify scope of guidelines

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/silver#102]
From https://www.w3.org/2002/09/wbs/94845/Silver-ED-21-01-2020/results#xq3

It remains unclear whether the guideline addresses documents / electronic pages or also software.
It should be clearly and centrally stated that Silver applies also to applications, including buiness applications, "Complex Web applications".
Currently, it seems to address only web sites with simple pages.
Similarly, it shoud be explicitly stated whether Silver also applies to ICTs or not.
In the latter case it should be described what should be done.

For the document/page/software reviewer (the target reader of the final guideline) it remains unclear what to find where, how to work with the document and which kind of pages is addressed.
In later parts of the documents, in some places web applications are named, in other explicitly web documents.

It feels like it needs to end with a statement about what Silver is tackling, perhaps linking to the explainer...

**Comment by jspellman** [comment]
done in FPWD
