### ISSUE TITLE
Introduction shouldn't delve too much into history

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/silver#104]
From https://www.w3.org/2002/09/wbs/94845/Silver-ED-21-01-2020/results#xq3

Most people using the guidelines don't need to know their history, I would move this to an appendix and focus the intro on basic info someone who is new to the topic, such as a product manager, needs to know to make sense of the document.

Perhaps a little less history would simplify it as an introduction, and if important, move to a history section or appendix.

**Comment by jspellman** [comment]
aw, all right.  We can take out the history.  Done in FPWD
