### ISSUE TITLE
User ID and Status

### ISSUE THREAD

**Issue by mikecrabb** [w3c/silver#112]
# General Description
Users of any platform immersive, gaming or telecoms need to be identifiable - as well as their status such as muted, or talking, present etc.

# Notes
This is essentially some kind of polling mechanism that could be linked with messaging via system level alerts and notifications?

# Associated Documentation
Based on:

- [https://www.w3.org/TR/raur/#incoming-calls-and-caller-id](https://www.w3.org/TR/raur/#incoming-calls-and-caller-id)
- [https://www.w3.org/TR/raur/#call-participants-and-status](https://www.w3.org/TR/raur/#call-participants-and-status)

# Functional Performance
Please see [EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf) for descriptions of functional performance areas.

- [x] Usage without vision
- [x] Usage with limited vision
- [ ] Usage without perception of colour
- [ ] Usage without hearing
- [ ] Usage with limited hearing
- [ ] Usage without vocal capability
- [ ] Usage with limited manipulation or strength
- [ ] Usage with limited reach
- [ ] Minimize photosensitive seizure triggers
- [ ] Usage with limited cognition
- [ ] Privacy

**Comment by charleshalldesign** [comment]
The Functional Needs Subgroup is currently aggregating and compiling and extending a list of needs beyond the scope of the EN 301 549 Functional Performance Statements. This is intended to get consensus from many W3C groups contributing to and relying on this information. 

It combines at least the following W3C sources: MAUR; XAUR; ARIA-AT; FAST; and COGA Functions. It also notes and considers at least the following external resources: EN 301 549 Functional Performance Statements; CVAA (47 CFR §14.21 - Performance Objectives); ISO 9241-171:2008 Ergonomics of human-system interaction
(Part 171: Guidance on software accessibility); and IMS Global Learning Consortium – Accessibility Background (§2.1 Disabilities, Functional Limitations, and Accessibility Tips).

**How should the output of this work be captured in the list of User Needs for this subgroup?**

**Comment by mikecrabb** [comment]
Applies if live captioning as it would have to identify the speaker

**Comment by RealJoshue108** [comment]
Strong +1 to being able to ping and get details of the speaker, their position etc. Good catch @mikecrabb 😊 [relates to https://www.w3.org/TR/raur/#call-participants-and-status]

**Comment by mikecrabb** [comment]
Additional information regarding **position** will be important for captioning in XR

**Comment by jspellman** [comment]
This issue was part of an organization attempt that failed.  Good ideas for a future draft
