### ISSUE TITLE
Interaction and target customization

### ISSUE THREAD

**Issue by mikecrabb** [w3c/silver#119]
# General Description
A user with limited mobility may need to be able to hit a larger 'Target size' for a button or other controls in immersive environments.

**REQ 4a:** Ensure fine motion control is not needed to activate an input.

**REQ 4b:** Ensure hit targets are large enough with suitable spacing around them.

**REQ 4c**: Ensure multiple actions or gestures are not required at the same time to perform any action.

- [https://www.w3.org/TR/xaur/#user-needs-definition](https://www.w3.org/TR/xaur/#user-needs-definition)

# Functional Performance
Please see [EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf) for descriptions of functional performance areas.

- [ ] Usage without vision
- [ ] Usage with limited vision
- [ ] Usage without perception of colour
- [ ] Usage without hearing
- [ ] Usage with limited hearing
- [ ] Usage without vocal capability
- [ ] Usage with limited manipulation or strength
- [ ] Usage with limited reach
- [ ] Minimize photosensitive seizure triggers
- [ ] Usage with limited cognition
- [ ] Privacy

**Comment by bruce-usab** [comment]
As noted on call 6/8:  XR captioning controls will need to honor user needs for interaction and target customization.
