### ISSUE TITLE
Voice Commands

### ISSUE THREAD

**Issue by mikecrabb** [w3c/silver#120]
# General Description
A user with limited mobility may want to be able to use Voice Commands within the immersive environment, to navigate, interact and communicate with others in XR environments.

**REQ 5a:** Ensure Navigation and interaction can be controlled by Voice Activation.

- [https://www.w3.org/TR/xaur/#user-needs-definition](https://www.w3.org/TR/xaur/#user-needs-definition)

# Functional Performance
Please see [EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf) for descriptions of functional performance areas.

- [ ] Usage without vision
- [ ] Usage with limited vision
- [ ] Usage without perception of colour
- [ ] Usage without hearing
- [ ] Usage with limited hearing
- [ ] Usage without vocal capability
- [ ] Usage with limited manipulation or strength
- [ ] Usage with limited reach
- [ ] Minimize photosensitive seizure triggers
- [ ] Usage with limited cognition
- [ ] Privacy

**Comment by mikecrabb** [comment]
Potentially relevant - awaiting feedback from @jspellman

**Comment by bruce-usab** [comment]
People using voice recognition for input (i.e., Dragon Naturally Speaking) typically want textual confirmation of what they said.  This is true not only for dictation, but voice commands as well.

The mechanism for textual confirmation of voice commands _might or might not_ make use of mechanism used for displaying captioning.
