### ISSUE TITLE
Text description transformation

### ISSUE THREAD

**Issue by mikecrabb** [w3c/silver#125]
# General Description
A deaf or hard of hearing person, for whom English or any other written language, may not be their first language and may have a preference for signing of text alternatives or equivalents.

**REQ 10a**:Allow object or item text descriptions to be presented to the user via a signing avatar.

- [https://www.w3.org/TR/xaur/#user-needs-definition](https://www.w3.org/TR/xaur/#user-needs-definition)

# Functional Performance
Please see [EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf) for descriptions of functional performance areas.

- [ ] Usage without vision
- [ ] Usage with limited vision
- [ ] Usage without perception of colour
- [ ] Usage without hearing
- [ ] Usage with limited hearing
- [ ] Usage without vocal capability
- [ ] Usage with limited manipulation or strength
- [ ] Usage with limited reach
- [ ] Minimize photosensitive seizure triggers
- [ ] Usage with limited cognition
- [ ] Privacy

**Comment by bruce-usab** [comment]
As noted on call 6/8:  This was put into _relevant for XR captioning_ category as **signing avatars** are more of a potential possibility in XR than they are with _traditional captioning_.
