### ISSUE TITLE
Reset focus and orientation

### ISSUE THREAD

**Issue by mikecrabb** [w3c/silver#128]
# General Description
 A screen magnification user or user with a cognitive disability or learning impairment may easily lose focus and be disorientated in immersive environments.

**REQ 13a:** Ensure the user an reset and calibrate their orientation/view in a device independent way.

**REQ 13b:** Ensure field of view in Immersive environments, are appropriate, and can be personalised - so users are not disorientated.

- [https://www.w3.org/TR/xaur/#user-needs-definition](https://www.w3.org/TR/xaur/#user-needs-definition)

# Functional Performance
Please see [EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf) for descriptions of functional performance areas.

- [ ] Usage without vision
- [ ] Usage with limited vision
- [ ] Usage without perception of colour
- [ ] Usage without hearing
- [ ] Usage with limited hearing
- [ ] Usage without vocal capability
- [ ] Usage with limited manipulation or strength
- [ ] Usage with limited reach
- [ ] Minimize photosensitive seizure triggers
- [ ] Usage with limited cognition
- [ ] Privacy

**Comment by bruce-usab** [comment]
May be an issue with Traditional Captioning.  Certainly an issue with XR captioning as avoiding vertigo is a problem.
