### ISSUE TITLE
Interaction speed

### ISSUE THREAD

**Issue by mikecrabb** [w3c/silver#130]
# General Description
Users with physical disabilities or cognitive and learning disabilities may find some interactions too fast to keep up with or maintain.

**REQ 15a:** Allow users to change speed at which they travel through an immersive environment, or can perform interactions.

**REQ 15b:** Allow timings for interactions or critical inputs to be modified or extended.

**REQ 15c:** Provide an XR angel or helper for the user with a cognitive or learning disability.

**REQ 15d:** Provide clear start and stop mechanisms.

- [https://www.w3.org/TR/xaur/#user-needs-definition](https://www.w3.org/TR/xaur/#user-needs-definition)

# Functional Performance
Please see [EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf) for descriptions of functional performance areas.

- [x] Usage without vision
- [x] Usage with limited vision
- [ ] Usage without perception of colour
- [ ] Usage without hearing
- [ ] Usage with limited hearing
- [ ] Usage without vocal capability
- [x] Usage with limited manipulation or strength
- [x] Usage with limited reach
- [ ] Minimize photosensitive seizure triggers
- [x] Usage with limited cognition
- [ ] Privacy

**Comment by bruce-usab** [comment]
Interaction speed is an issue with traditional captioning, but it is pretty well addressed.  Many of the UIs let the user pause and/or rewind the textual display.  Of course, real-time events may impose practical limits to this.

As noted on the call 6/8:  Interaction speed is very much an issue in an XR setting.  The challenges associated with traditional captioning are significantly multiplies.
