### ISSUE TITLE
Avoiding sickness triggers

### ISSUE THREAD

**Issue by mikecrabb** [w3c/silver#131]
# General Description
Users with vestibular disorders, Epilepsy, and photo sensitivity may find some interactions trigger motion sickness and other affects.

**REQ 16a:** Avoid interactions that trigger epilepsy or motion sickness and provide alternatives.

**REQ 16b:** Ensure flickering images are at a minimum, will not trigger seizures (more than 3 times a second), or can be turned off or reduced.

- [https://www.w3.org/TR/xaur/#user-needs-definition](https://www.w3.org/TR/xaur/#user-needs-definition)

# Functional Performance
Please see [EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf) for descriptions of functional performance areas.

- [ ] Usage without vision
- [ ] Usage with limited vision
- [ ] Usage without perception of colour
- [ ] Usage without hearing
- [ ] Usage with limited hearing
- [ ] Usage without vocal capability
- [ ] Usage with limited manipulation or strength
- [ ] Usage with limited reach
- [ ] Minimize photosensitive seizure triggers
- [ ] Usage with limited cognition
- [ ] Privacy

**Comment by mikecrabb** [comment]
May apply to captioning. Caption window can't _jiggle_ and needs to be static

**Comment by bruce-usab** [comment]
Definitely applicable to XR captioning, as where to put the captioning is an issue for avoiding vertigo.

**Comment by CharlesBelov** [comment]
It would be good to add the following items not covered by the original post, with appropriate word-smithing:

Usage with attention deficit
Usage with vestibular disorder
Usage with hypervigilance
Usage with altered perception of color
