### ISSUE TITLE
Binaural (Spatial) audio track alternatives

### ISSUE THREAD

**Issue by mikecrabb** [w3c/silver#132]
# General Description
 Deaf and hard of hearing users may need binaural recordings of audio content in order to perceive it.

**REQ 17a**: Provide alternative binaural audio recording tracks to emulate 3 dimensional sound forms in immersive environments.

- [https://www.w3.org/TR/xaur/#user-needs-definition](https://www.w3.org/TR/xaur/#user-needs-definition)

# Functional Performance
Please see [EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf) for descriptions of functional performance areas.

- [ ] Usage without vision
- [ ] Usage with limited vision
- [ ] Usage without perception of colour
- [ ] Usage without hearing
- [ ] Usage with limited hearing
- [ ] Usage without vocal capability
- [ ] Usage with limited manipulation or strength
- [ ] Usage with limited reach
- [ ] Minimize photosensitive seizure triggers
- [ ] Usage with limited cognition
- [ ] Privacy

**Comment by mikecrabb** [comment]
Binaural audio = Spatial Audio

**Comment by bruce-usab** [comment]
Note from call 6/8:  Captioning will need to convey directional or other information conveyed with Spatial Audio.
