### ISSUE TITLE
Subtitling customization

### ISSUE THREAD

**Issue by mikecrabb** [w3c/silver#133]
# General Description
Users with vision impairments may need to customise subtitles and other text in immersive environments.

**REQ 18a**: Allow customisable context sensitive reflow of text and subtitled content in XR spaces. The suitable subtitling area may be smaller than what is required currently for television

- [https://www.w3.org/TR/xaur/#user-needs-definition](https://www.w3.org/TR/xaur/#user-needs-definition)

# Functional Performance
Please see [EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf) for descriptions of functional performance areas.

- [x] Usage without vision
- [x] Usage with limited vision
- [ ] Usage without perception of colour
- [ ] Usage without hearing
- [ ] Usage with limited hearing
- [ ] Usage without vocal capability
- [ ] Usage with limited manipulation or strength
- [ ] Usage with limited reach
- [ ] Minimize photosensitive seizure triggers
- [ ] Usage with limited cognition
- [ ] Privacy

**Comment by bruce-usab** [comment]
As noted on call 6/8:  This was put into Traditional Captioning as it is something that would be expected outside of XR setting.

**Comment by mikecrabb** [comment]
Whilst important to consider customisation interface within XR - this would be an interface issue. However, when we look at contextual awareness this will become an enhanced XR issue
