### ISSUE TITLE
Requirments updates

### ISSUE THREAD

**Issue by alastc** [w3c/silver#186]
Hi,

I'm posting this on behalf of someone who doesn't have access to github, it is not my ideas or work:
<hr>
Updates in CAPS.

**1 - Intro:** People with PERMANENT, TEMPORARY and RECURRING disabilities can face problems using online content and applications.
(So no need for a second sentence or mention of limitations.  Barriers is a better word than limitations anyway, as it is about the problem rather than the individual).

**Design principle 1:** Support the needs of an INCREASINGLY wide range of people with disabilities...
(this helps with iteration and concerns about how wide is wide enough, etc.)

**2 - Emerging tech** - you included AR/VR etc but not IoT/smart tech and AI/ML. This is going to be so important in accessibility going forward, I'm not really sure how it can be left off.  Actually customization/personalization technologies could also be included in emerging tech; is that possible to add to the requirement in this context?

**Scope:** flexibility to include emerging technologies, such as AR/VR/XR, voice assistants AND OTHER IOT/SMART TECHNOLOGY.
(which will cover ML/AI in back-end)

**Maintenance:** Evolving Technology: ....and the introduction of new modalities like surface reaction, ultrahaptics, AND NEWLY PERSONALIZED DIGITAL SERVICES BASED ON PREDICTIVE AND PRESCRIPTIVE MACHINE LEARNING.

**Design Principle 5 - Plain Language:**
SILVER CONTENT WILL be written in plain language SO THE INTENT AND EXPECTATIONS ARE as easy as possible to understand.  PLAIN LANGUAGE REDUCES COGNITIVE AND LANGUAGE BARRIERS AND FACILITATES MULTI-STAKEHOLDER AND TEAM COMMUNICATION ABOUT ACCESSIBILITY.  SILVER GUIDANCE WILL BE WRITTEN, WHEREVER POSSIBLE, FOR A DIVERSE AUDIENCE, INCLUDING THOSE NOT SPECIALIZED IN ACCESSIBILITY AND THOSE WITHOUT TECHNICAL EXPERTISE.

**Comment by jspellman** [comment]
We took the comment and broke it into 5 sections: 
Resolutions from the Silver meetings:  
[RESOLUTION: Accept change to Intro of Silver Requirements as amended: People with permanent, temporary and recurring disabilities experience difficulties and barriers using online content and applications.](https://www.w3.org/2020/12/08-silver-minutes.html#resolution01)
