### ISSUE TITLE
Can the intro provide more context?

### ISSUE THREAD

**Issue by mbgower** [w3c/silver#19]
This is great work, but I do have some overarching observations I thought it might be easiest just to capture.

### Introduction
> People with disabilities can face problems using online content and applications. 

I was surprised to see the word "online" in this first statement. I thought Silver was being scoped beyond web content?  If so, I think clarity around exactly what is meant by 'online' would be useful. Maybe it's still confined only to UIs that receives or transmits information through the Internet? 

I was a bit surprised by the constraints in these two bullets
> We need guidelines to:
    identify these barriers encountered by people with disabilities.
    explain how to solve the problems they pose.

It seems to me we need more than that, and it may be better to define the scope of what is needed here, before going on to define the problems.

In my mind, I had been thinking that a standard that aims to be significantly broader in scope, would likely need to invert its problem statement. For instance, with the fragmentation of UI into any number of customized modalities and restricted use cases, doesn't it make sense to define what any given delivery system _can_ do? 

- We need guidelines to indicate the capabilities of any specific user interface 
- We need guidelines to indicate the totality of a device's capabilities

In example, a refrigerator or other major appliance may have a reduced-function UI mounted on the door. That UI may be output-only (with inputs coming from fridge activity and environment), or it may have a few user input mechanisms.  There may also be manual controls inside the fridge that allow the operator to control some functions (such as temperature or humidity) in response to information revealed on that UI. Obviously the operator can manually add and remove things from the fridge, possibly in response to prompts (i.e., if the UI tells the operator they are out of milk). But the degree to which some such UI information is _necessary_ to the operation of the fridge is debatable, as is whether it should be governed by Silver. Likely there will be a _bunch_ of IoT information, some of which will be available via a web or mobile application, and some of which may be more or less important to the operation of the fridge.

There are a lot of use cases within that, based on user need, user ability, appliance features, etc. There are also considerations for the device itself, which if we _are_ extending considerations beyond the web, likely need to come into play. If I'm in a wheelchair, I may care about door's arc, the reach height for its shelving, or the extension length of the bottom freezer door.

To what extent does the form factor of a device enter into considerations for its 'online' accessibility? In example, with WCAG we were able to more or less assume an external keyboard and screen. Can we assume screens? Input pads? Does a feature-rich app with a reduced voice-controlled interaction constitute a failure? Does an app with an enhanced voice-controlled interaction constitute a failure? (i.e., is there _always_ a need to have equivalent facilitation in every modality for something to be considered to pass Silver?)  Does the fact a kiosk's controls may not be within the reach of someone in a wheelchair need to enter into Silver's considerations?

--

Without an introduction that gives the context of a more complex world beyond using-the-web-on-a-desktop-browser, the problem statements seem to have focus on 'what is wrong with WCAG 2.x?'

That's a good question to ask (and answer), but I believe it is a subset of what Silver's requirements are. I also think it is biasing Silver to focus on what any interface should do, instead of focusing on indicating what an interface _can_ do.

Few UIs are going to be able to satisfy the needs of every individual. Many, by design, will be targetted at one modality. Rather than 'fail' that UI for all the things it cannot do, one possible way of positioning Silver is to provide simple tools for describing what a solution is intended to do, and what it is capable of doing from an accessibility perspective (i.e., by function, by modality, by sense/capability).  Can someone blind use this fridge? Can someone in a wheelchair use this fridge? What different features and components of the fridge are understandable by someone who reads at an elementary level?

By leading with simple statements, potentially much of the complexity with 2.0 could be offered at lower levels where it makes sense. 

This is just one riff, obviously. I'm not trying to position solutions, but trying to make the point that to define the Silver Requirements, I think a bit more background is needed, to ensure folks ask the questions necessary to get the best solution and implementation. For the Problem statements, I'll break any feedback down into discrete Issues so they can be dealt with or dismissed on a granular basis.

PS I note in the [Draft Final report ](https://www.w3.org/community/silver/draft-final-report-of-silver/) there are a bunch of statements which suggest the above is close to some of the thinking going on:
> Create a solution that addresses the needs of people to find information by role, problem, by disability, and by platform.  How can people discover what they need to know?

> Develop scorecard or rubric measures for testing task accomplishment, instead of technical page conformance.

> Develop a point and ranking system that will allow more nuanced measurement of the content or product:

**Comment by mbgower** [comment]
@jspellman just wanted to make sure you'd seen this. Since I missed the survey deadline, I'd been intending to provide feedback through these issues. Does that work?

**Comment by jspellman** [comment]
@mbgower I was just reading it.  I had not seen it earlier (my bad), and am not going to be able to include it in the draft you will see in AGWG on the 10th, since the Silver team hasn't had a chance to comment on it.  I will raise this at the Silver meeting on the 10th.  I think we have addressed at least some of the points you are raising.  Thank you for such a thoughtful comment.  :)

**Comment by jspellman** [comment]
1. "online" changed to "digital".  We are really not ready to take on the scope argument yet. We want to plan Silver so it can be used by a broad scope. The actual scope for chartering Silver will probably not be addressed for until mid-2019. 
2.  I'm working on the rewrite of the intro with your comments.  I am looking at the text you have:
>  We need guidelines to indicate the capabilities of any specific user interface
>  We need guidelines to indicate the totality of a device's capabilities

I'm having a hard time visualizing what you mean by "indicate".  I agree with your explanation, but I'm looking for a more clear link from your explanation to the bullet points we want to insert.  Do you mean that you want to someone with a disability to have a label that "this refrigerator can be used by people who are blind"?  What is the difference between the capabilities of the user interface, and the totality of the device capabilities?

**Comment by mbgower** [comment]
> I'm having a hard time visualizing what you mean by "indicate". 

At the moment, the accessibility conformance report (aka VPAT) is not very user friendly and  does not allow anyone to easily identify whether a product will be usable by a specific individual (unless it is a completely clean report).

So I was envisioning more focus on results that easily (and hopefully intuitively) wrap up to easily represent the 'passes' from a user perspective. One possible example would be a stamps that validate a product for established disability types -- possibly indicating degrees of usability (sorta like the A - AAA levels).

> What is the difference between the capabilities of the user interface, and the totality of the device capabilities?

As per my example, when you begin to address physical objects (i.e., something beyond standard form factor computers). there way well be considerations for direct interaction with the object as well as between the various UIs available for an object. A physical device is likely going to have limitations in design for some users. I as a user may be interested in how much I would be able to interact with the primary modality of a device, and when and to what degree I'm going to have to rely on a different UI (mobile app, web page, dedicated remote) to complete certain tasks.

**Comment by jspellman** [comment]
@mbgower, this is important and probably should be included in Silver.  It was discussed at the Silver Design Sprint, but no one worked on it in detail.   We aren't ready to put this in the Requirements yet.  I have added a project to look at this issue for the Silver prototypes.  Would you like to work on it and can you put some people together to look at this in more detail?  I will ask at the next Silver meeting.  There may be some people in AGWG who would like to work on it.  We should probably send an email to the Silver email list to see if there are people interested in working on this.

**Comment by jspellman** [comment]
@mbgower , the Silver group discussed your ideas briefly in the meeting today.  We are putting your simple comments on Silver Requirements into the next draft, and so want to close this issue.  The issues you raise about certification and informing people with disabilities whether a product or digital content works for their functional abilities will be a new Issue on the Conformance prototype.  https://www.w3.org/2018/07/27-silver-minutes.html#resolution01

**Comment by jspellman** [comment]
Moved this discussion to Conformance Prototype Issue #36
