### ISSUE TITLE
Large / dynamic digital products and WCAG 3.0

### ISSUE THREAD

**Issue by spanchang** [w3c/silver#218]
The size of the digital product being evaluated or the  frequency with which the entire product or part thereof undergoes changes should not be a factor for a technical standard.  
Example: 
- The PDF/UA  standard applies to a PDF that is 3 pages long as well as 300 pages long, or
- the international  (or country specific) accounting / financial standards is one standard. It applies to an enterprise with a revenue of tens of millions of dollars (or Euros) in revenue as well as  to a multi-billion one.

For a large bank or insurance or university with hundreds  of pages or views, it is up to the enterprise to determine the  scope of the accessibility evaluation.  
Consider, in a bank, the division that deals with personal banking  seldom talks to the division that handles investment banking or business accounts or credit card processing or mortgage loans. They are mostly managed by  independent teams and set their own priorities, goals. True there may be one CIO for the bank.
So the scope of accessibility assessments are also  set independently.

It is up to the enterprise  to define the scope of the evaluation. 
It is also up to the enterprise to institute  processes that ensure  that accessibility does not break when changes are introduced at whatever frequency they choose.
Those processes may be fully internal or may involve a team of  external accessibility professionals embedded into their SDLC processes.
Again from the finance/accounting world:  auditors audit and certify the balance sheet and income statement periodically. That certification does not extend to a future quarter or year which needs to be certified again.
It is the responsibility of the enterprise' management to  ensure that  digital content is accessible. And they take ownership for a conformance claim.
An external firm can only test and certify (if requested) that the content (views / processes)  that the firm evaluated as per their contract meets WCAG requirements as of a particular date.
So WCAG should not be concerned with the size of the digital product or frequency / nature of changes IMO while setting out technical and functional accessibility requirements.
Thanks,
Sailesh

**Comment by jspellman** [comment]
Thank you for your comment. That is the direction that we want to go: to have one standard that applies from very small to very large.  Because of their different needs, we may not be able to keep to that, but for this draft, we have just one standard that applies to all organizations.
