### ISSUE TITLE
About "substantially conformant"

### ISSUE THREAD

**Issue by spanchang** [w3c/silver#219]
Reference (from Problem Statement doc): All software – and likewise all dynamic websites – of large enough size or complexity has bugs; this is unfortunately unavoidable.  Websites that meet the solution should have no greater acceptance of accessibility bugs as the site has for bugs generally, nor should accessibility bugs be disproportionately represented among the number or severity of bugs found. 
Comment:
I disagree. We are  discussing about accessibility  that prevents access or makes access difficult.
Will a website launch if  the credit card field  expects  16 digits for an American Express card (which is only 15 digits) and fails to proceed to the next step?
Likewise, when a company wants an  accessibility certification, they have the choice to meet WCAG 2.0 or 2.1 or 3.0 at Level A or AA for WCAG 2.X (though AA is customary).
Now if there is a data table and  row headers are not marked up in the latest update to their application, it is not a complete blocker for the particular view, but if the company has committed to meet SC 1.3.1 as part of the conformance certification they are after, why should not the certification be denied?

Attempting to define "substantially / reasonably conformant" after setting out  conformance requirements (Bronze / Silver / Gold) is a slippery slope which should be avoided.

Please refer to athought for defining Bronze - silver- gold levels at
https://github.com/w3c/silver/issues/217

Thanks and humbly,
Sailesh

**Comment by sajkaj** [comment]
Salish: The Conformance Options subgroup discussed your comment on our telecon this week. We agree that whatever we propose needs address your concern, because we share that concern. We note that no proposal has yet been made. The document you reference is a draft working document. We would invite you to revisit this concern once there's text in a WCAG 3 WD.
