### ISSUE TITLE
Silver Requirements: 1.2. Broader Scope

### ISSUE THREAD

**Issue by spanchang** [w3c/silver#224]
Reference: Requirements for Silver Nov 18, 2020 Draft, item 1.2. Silver Scope - broader scope: 
Please can the requirements doc include rationale for covering more than just content (i.e. websites, software / applications and such)? The scope extends to:
- authoring tools, such as content management systems
- user agents, such as browsers and media players
- assistive technologies, such as screen readers, screen magnifiers, and assistants for memory, organization, or simplification
- operating systems and other platforms who may want advice for features to better support people with disabilities

So long as it is limited to the accessibility of the UIs of authoring tool / browser / OS, it is fine. 
But attempting to cover what features an authoring tool / browser /OS should offer to facilitate / enhance accessibility as part of a guideline that covers content will make the guideline very very vast and increase complexity for comprehension and navigation.
The ATAG, UAG have been separate guidelines for valid reasons all these years, so what has changed now?  
Content designers and developers who account for 99+ percent of users who will use these guidelines  are completely dependent on what features platforms / user agents / OS / platforms offer and author content accordingly.
Guidance on how OS / platforms / authoring tools and user agents should be built to aid accessibility is a completely different cup of tea and is the domain of a very small set of IT folk engaged in that specialized field. It is irrelevant for designers and developers of content.     
The statement at the end of the doc, "Our intent is to provide guidance for a diverse group of stakeholders including content creators, browsers, authoring tools, assistive technologies, and more" is quite scant as a justification for this major shift.
The Requirements doc should address this "broader scope" explicitly with detailed justification if Silver has to continue down this path. 
Thanks,
Sailesh

**Comment by alastc** [comment]
AC needs to create a PR for this one.

**Comment by alastc** [comment]
Approved from [meeting](https://www.w3.org/2024/03/05-ag-minutes) and 5 day window.
