### ISSUE TITLE
Silver scope covers closed systems / kiosk UIs?

### ISSUE THREAD

**Issue by spanchang** [w3c/silver#225]
Cancontent accessibility guidelines explicitly apply to user interfaces of closed systems and kiosks?  
e.g. table ordering tablet like Ziosk, or an exercise bike's tablet (e.g. Peloton), a gas or petrol dispensation station with features for fleet maintenance, a grave locator kiosk in a cemetry and so on.
And what about a TV?  Menus and input fields etc. presented by apps? 
Some of these devices / TVs work with a bluetooth keyboard too.
I do not mean hardware aspects of the kiosk.
The scope should touch upon this topic?
Thanks,
Sailesh

**Comment by jspellman** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by alastc** [comment]
Draft response:
<hr>
The goal for WCAG 3.0 is to provide information that can be used to improve the accessibility of products when using the guidelines on a variety of platforms. As noted in the [Draft Requirements](https://w3c.github.io/silver/requirements/), it will use a different framework to allow it to address more disability needs, address publishing requirements and emerging technologies on the web such as web XR (augmented, virtual and mixed reality) and voice input.  

It does not intend to apply to closed systems, however, like WCAG2ICT  that mapping exercise could be conducted at a later point to fill in the gaps.
