### ISSUE TITLE
Method for Decorative Images has a decorative image with alternative text

### ISSUE THREAD

**Issue by yatil** [w3c/silver#235]
I’m still wrapping my head around the draft and its sheer complexity and difference from what we're used to have, but I could not not notice that the Method pages have a decorative icon with the alternative text “method” directly before the heading starting with “Method:”.

This is also true for the method page that describes methods for coding decorative images:

![Screenshot of the page, with highlighted alternative text.](https://user-images.githubusercontent.com/58862/105380768-8ffdbb00-5c0e-11eb-8d03-84fcbeeff0bd.png)

The alternative text Silver in the link to the Guidelines draft might also not be sufficient.

**Comment by patrickhlauke** [comment]
sigh

**Comment by michael-n-cooper** [comment]
I think it's debatable whether those images are "decorative", but I get the alt text is redundant with immediately adjacent text, so I've set it to null. I expect these pages to be completely redesigned from scratch this year anyways.
