### ISSUE TITLE
7.1 Meaningful Text Alternatives

### ISSUE THREAD

**Issue by gregrgay** [w3c/silver#257]
This guideline should state up front that a "meaningful" text alternative is required, rather just a text alternative. Recognizing that decorative images may not be meaningful, then perhaps "appropriately meaningful" or "appropriate" or "equivalent" would generalize better to more situations. Working with novice content developers (i.e. online instructors), too often they miss the need for "meaningful" using alt text like "graph" without explaining a graph of what, or "painting" without describing what's in the painting. 

The word 'appropriate' in used throughout the description of the guideline, though the word is not defined. Appropriate could be define as "meaningful in the sense that those listening to the text alternative should take away "equivalent information" to those who are viewing it". Scoring could be based on the extent to which "appropriate" or "equivalent" is true.

There is also an aspect of "context" that should reflected in this guideline. The same image may reflect different information based on the context. We often use an example of a graph that shows population grow over a 100 year period. In a social science course, the text description might describe how population grow is represented in the graph. In a statistics course however, in a graph construction lesson, the text description might talk about how the graph is created, with axes, labels, lines, etc.

**Comment by MakotoUeki** [comment]
DRAFT Response (27th April, 2021):
Thank you for your comment and suggestion. While we agree with the points raised, the title should be kept as-is. A method document will provide an explanation on how to meet the guideline. This document will provides concrete examples of how to meet the guideline, with clear examples of what is meant with "appropriate," "equivalent" or "meaningful." We will keep your points in our mind.

**Comment by alastc** [comment]
Outcome from the AG meeting:

- Consider including an adjective.
- Consider separating the requirements for (automatable) "does it have alt text", and then is it useful alt text.

**Comment by WilcoFiers** [comment]
Thank you for reviewing and commenting on the WCAG 3 first public working draft. We have an [updated working draft](https://www.w3.org/TR/wcag-3.0/) and the group is starting a new workflow process. To facilitate this transition we have recorded your concern as part of w3c/wcag3#20. You can engage in the discussion around this issue there. 

Please continue to review future drafts and provide feedback through [Github](https://github.com/w3c/wcag3).

If you disagree with closing this issue, please reopen it and add your reasons for reopening it to the comments.
