### ISSUE TITLE
7.4 Sematically Defined Sections, Headings, & Subheadings

### ISSUE THREAD

**Issue by gregrgay** [w3c/silver#260]
I do agree with the need for the visual appearance of headings to aid understanding for those who can see,  though this guideline should highlight semantically structured headings first, as a bronze level requirement, over the visual appearance of headings and the visual appearance of nesting. The use of styled text to create the appearance of headings, I believe should be a fail for this guideline, or at least scored low, in the absence of semantics.  Semantic headings are critical in most cases for screen reader users, for navigation and understanding.  

By default using semantic headings produces the visual appearance of headings and the presence of nesting. So, there is little reason to choose styled text for headings over properly marked up semantic headings. In terms of scoring, it would be more of question of whether change from the default styles for semantic headings, maintains the appearance of nesting.

...understanding that this guideline is still a work in progress.

**Comment by chaals** [comment]
There are cases where styling can lead to visual presentation that doesn't match the underlying semantics presented e.g. to a screen reader. This was the problem with the "implementations" of the proposal to use h1 everywhere. That should be a "critical error"

**Comment by jenstrickland** [comment]
The structured content sub-group agrees with both of these comments and will include them in our work. Thank you for your insightful comments!
