### ISSUE TITLE
Review and reconsider the wording that introduces some lists

### ISSUE THREAD

**Issue by EmmaJP** [w3c/silver#264]
The are several places through the "Clear words" How to documentation where the wording used to introduce a list jars grammatically with the wording used within the list. This is particularly jarring in places where the wording is intended to prepend each item in the list, as though the list item finishes the sentence (which should also conclude with a full stop). I've included a few examples below, though it may be worth reviewing WCAG 3.0 more widely with this in mind.

https://www.w3.org/WAI/GL/WCAG3/2020/how-tos/clear-words/ 

"Summary" tab includes the phrase "Writing and editing in plain language means using:" which works well grammatically with the first item in the list but not the following items. For example 'Writing and editing in plain language means using define terms' does not make sense, neither would 'Writing and editing in plain language means using avoid double negatives'.

"Design" tab uses "Ensure that..." to introduce a list where none of the phrases follow well. Perhaps something like 'Ensure that you...' 'design a glossary.' might work better ('you', 'a' and full stop intentionally added).

"Develop" tab uses ..."are accessible by:" to introduce phrases that start with "make inline" or "design one click". Perhaps something like 'Develop inline definitions to be accessible by ensuring they: - are keyboard accessible. - remain open once activated until the user closes them. - a visually distinct from a link.' etc.

**Comment by jspellman** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by jmcsorle** [comment]
Thank you for your comment. Your are correct. We will make corrections to the language to make it grammatically correct.

**Comment by alastc** [comment]
@jspellman once you the updates from the survey are included, the PR can be merged and the issue closed.

**Comment by WilcoFiers** [comment]
Thank you for reviewing and commenting on the WCAG 3 first public working draft. Based on your feedback and that of others, the Accessibility Guidelines Working Group revised the approach to WCAG 3. You can see the current proposed approach and current status in the [updated working draft](https://www.w3.org/TR/wcag-3.0/).

Please continue to review future drafts and provide feedback through [Github](https://github.com/w3c/wcag3).

If you disagree with closing this issue, please reopen it in https://github.com/w3c/wcag3/issues and add your reasons for reopening it to the comments.
