### ISSUE TITLE
Abstract - Plain Language suggestion

### ISSUE THREAD

**Issue by msellon** [w3c/silver#290]
Suggestion to simply the first sentence:

> The Requirements for WCAG 3.0 document is the next phase in the development of the next major upgrade to accessibility guidelines that will be the successor to Web Content Accessibility Guidelines (WCAG) 2 series.

to:

>The Requirements for WCAG 3.0 documentation is the next phase of development of the next major upgrade to accessibility guidelines. WCAG 3.0 will be the successor to the Web Content Accessibility Guidelines (WCAG) 2 series. 

or
>The Requirements for WCAG 3.0 documentation is the next phase of development of a major upgrade to the Web Content Accessibility Guidelines (WCAG) 2 series.

**Comment by lauracarlson** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by jspellman** [comment]
PR #619

**Comment by slauriat** [comment]
Thank you for comment! We've incorporated changes into pull request #619 to address.

**Comment by alastc** [comment]
[Diff between #619 and main](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fsilver%2Fmain%2Frequirements%2Findex.html&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fsilver%2F7f06e6cc6261669461f5c673fdd986f240ba84cf%2Frequirements%2Findex.html).

**Comment by bbrown0** [comment]
Read the diff document. Minor edit, under the conformance model heading (#86/102): if we add "If we allow" the "Multiple" doesn't need to be capitalized.

**Comment by alastc** [comment]
Closed by #619
