### ISSUE TITLE
Styling inconsistency in punctuation of (un)ordered lists

### ISSUE THREAD

**Issue by msellon** [w3c/silver#295]
There is currently an inconsistency in the use of punctuation and (un)ordered lists in the document that should ideally be consolidated into a uniform style - either all (un)ordered lists end in a period, or none of them do.

For example, compare:

- Unordered list in 1. Introduction
- Ordered list in 1.1 Comparison to WCAG 2.x Requirements

**Comment by lauracarlson** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by jspellman** [comment]
This was not as simple as it might first appear.  We use ordered and unordered lists in different ways, so we could not convert all the unordered to ordered or vice versa without changing meaning.  However, I was able to make the punctuation consistent within each type. The unordered lists are the continuation of the prior sentence with lower case start, comma separated except for the next to last which is comma AND. The final item in the list has a period.  The ordered lists were changed to start with a capital letter and end with a period.  The unordered lists that are paragraphs are not changed.

**Comment by jspellman** [comment]
PR #619

**Comment by slauriat** [comment]
Thank you for comment! We've incorporated changes into pull request #619 to address.

**Comment by alastc** [comment]
Closed by #619
