### ISSUE TITLE
1.3 Silver Task Force Research - Plain Language suggestion

### ISSUE THREAD

**Issue by msellon** [w3c/silver#296]
Suggestion to simplify and clarify the second paragraph of section 1.3 Silver Task Force Research:

A recurring theme identified in the year of WCAG 3.0 research was the popularity and quality of the WCAG 2.0 guidance. Most of the opportunities identified in the research were improvements in the structure and presentation of accessibility guidance to improve usability, support more disability needs, and improve maintenance.

**Comment by lauracarlson** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by jspellman** [comment]
PR #619

**Comment by slauriat** [comment]
Thank you for comment! We've incorporated changes into pull request #619 to address.

**Comment by alastc** [comment]
Closed by #619
