### ISSUE TITLE
2.2 Conformance model -  change then to they

### ISSUE THREAD

**Issue by msellon** [w3c/silver#297]
There appears to be a typo in the third sentence of the opening paragraph of section 2.2:

>Then need to work together...

should be

**They** need to work together...

The sentence is also missing a period at the end, i.e.:

They need to work together, and that interplay will be governed by the design principles.

**Comment by lauracarlson** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by alastc** [comment]
Closed by #619
