### ISSUE TITLE
2.2 Conformance Model, Task-Based Assessment - Plain Language suggestion

### ISSUE THREAD

**Issue by msellon** [w3c/silver#299]
Suggested edit for Task-Based Assessment:

Moving away from strictly web pages and web sites as a collection of web pages, WCAG 3.0 could set the scope of conformance as a comprehensive set of tasks defined by the author of the site or application. A properly marked up button doesn't help **anybody** if the user can't complete the task at hand. Task-based assessment allows flexibility for **the** conformance of complex applications that are not conducive to component/tag assessment or **a** full-page assessment.

Original text:
>Moving away from strictly web pages and web sites as a collection of web pages, WCAG 3.0 could set the scope of conformance as a comprehensive set of tasks ~~as~~ defined by the author of the site or application. A properly marked up button doesn't help anything if the user can't complete the task at hand. Task-based assessment allows flexibility for conformance of complex applications that are not conducive to component/tag assessment or full-page assessment.

**Comment by lauracarlson** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by jspellman** [comment]
PR #619

**Comment by slauriat** [comment]
Thank you for comment! We've incorporated changes into pull request #619 to address.

**Comment by alastc** [comment]
Closed by #619
