### ISSUE TITLE
2.2 Conformance Model, Accessibility Supported - suggest to remove "the"

### ISSUE THREAD

**Issue by msellon** [w3c/silver#300]
Suggest to remove "the" from the first sentence:

- **Accessibility Supported:** As ~~the~~ technologies evolve, the interoperability of...

**Comment by lauracarlson** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by jspellman** [comment]
PR #619

**Comment by slauriat** [comment]
Thank you for comment! We've incorporated changes into pull request #619 to address.

**Comment by alastc** [comment]
Closed by #619
