### ISSUE TITLE
3. Design Principles #5 Plain language - definition suggestion

### ISSUE THREAD

**Issue by msellon** [w3c/silver#301]
For the definition of plain language, has the usage of a standardised test such as the Automated Readability Index (ARI) been considered? The ARI test tends to work well with English and Western European languages. It calculates a readability score based on word and sentence length, and matches the score to an equivalent reading ability level age, based on full-time education. 

If there is not a specific policy for reading age on the site, the best practice suggestion according to ARI is to aim for a score of 11 or higher, which is 15+ years of age.

More information is available on, for example, the[ Readability Formulas website](https://readabilityformulas.com/automated-readability-index.php).

**Comment by jpascalides** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by WilcoFiers** [comment]
Thank you for reviewing and commenting on the WCAG 3 first public working draft. We have an [updated working draft](https://www.w3.org/TR/wcag-3.0/) and the group is starting a new workflow process. To facilitate this transition we have recorded your concern as part of w3c/wcag3#21. You can engage in the discussion around this issue there. 

Please continue to review future drafts and provide feedback through [Github](https://github.com/w3c/wcag3).

If you disagree with closing this issue, please reopen it and add your reasons for reopening it to the comments.
