### ISSUE TITLE
Guidelines focus on functional user needs

### ISSUE THREAD

**Issue by putzhuber** [w3c/silver#311]
Guidelines will be more granular, more specific

### Proposal: 
Guidelines should focus as much as possible on special functional user needs, not mix very different needs, for instance structure (special need for screenreader users, machine readability) and styling (special visual needs) should not be grouped together.
### Some examples for separation of user needs (as far as possible)
**Guideline Content is semantically structured**

- Outcome: Headings organize content
- Outcome: Visual headings correspond with semantic headings
- Outcome: Conveys hierarchy with semantic structure
- Outcome: Paragraphs and lists structure content 
- Outcome: Landmarks convey sections of page
- Outcome: Use of standardized semantic elements for blocks of content
- Outcome: Use of lists for navigation
- Outcome: Use of standardized semantic markup for datatables
- ...

**Guideline Content is visually structured**

- Outcome: Uses visually distinct headings
- Outcome: Separates connected blocks of content visually
- Outcome: Follows recommendations for heights of margins between content blocks
- Outcome: Follows recommendations for line-length
- Outcome: Use of clear visual form labels
- ...

**Guideline Auditory content is structured and operable**

- Outcome: Background noise is xxxx lower than foreground speech
- Outcome: Sound does not start automatically
- Outcome: Sound is easily dismissable
- Outcome: information about sound is available

**Guideline Multimedia content that cannot be seen has alternatives**

- Outcome: Short Summary of video content available
- Outcome: Description of complex video available
- Outcome Audio Description for complex video content
- - ...

**Guideline Multimedia content that cannot be heard has alternatives** 

- Outcome: Transkript for audio content available
- Outcome: Captions for audio content in videos
- Outcome: Translation in sign language for video content
- - ...

**Guideline The function of elements is semantically clear and consistent**

- Outcome: conveys name, role and value of each element
- Outcome: form elements are labeled
- Outcome: links opening a different file format, convey this information in text 
- Outcome: conveys toggle function of links or buttons
- Outcome: markup follows specification (html5, aria, pdf/ua...)
- Outcome: navigation is consistent
- ...

**Guideline The function of elements is visually clear and consistent**

- Outcome: purpose of interactive elements (buttons, icons, links) is clear
- Outcome: form elements have visual labels
- Outcome: labels are clearly connected to form elements, even when page zoom up to 400% is used.
- Outcome: navigation is visually consistent
- ...

**Guideline Content is understandable**

- Outcome: use of clear words
- Outcome: appropriate level of specialist language
- Outcome: appropriate use of foreign words
- Outcome: explanation for abbreviations
- ...

and so on...

**Comment by jpascalides** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by jspellman** [comment]
Discussed in the SIlver meeting of 11 March 2022. RESOLUTION:  311 has some support in the group and needs more development, and will be assigned to "Outcome and Guidelines"

**Comment by alastc** [comment]
Response above approved by the group.
