### ISSUE TITLE
Clear Words

### ISSUE THREAD

**Issue by artist861** [w3c/silver#313]
Consistency of wording or phrasing is also important.

**Comment by lauracarlson** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by jmcsorle** [comment]
Draft Response:
<hr>
Yes, we agree that consistency in wording or phrasing is important. Using the term "consistency" in a standard, would require us to have a definition of "consistency" and that can be challenging, especially across multiple languages. We will continue to explore this, but it will probably not be in the next draft.

**Comment by lauracarlson** [comment]
Suggest adding at the end of the [draft response](https://github.com/w3c/silver/issues/313#issuecomment-820770709-permalink): "We will tag this issue to come back it to at an appropriate point later."

**Comment by alastc** [comment]
Updated draft: 
<hr>
Yes, we agree that consistency in wording or phrasing is important. We do also have WCAG 2.x criteria for "consistent", which will be brought into WCAG 3.x at a later stage.

Using the term "consistency" in a standard, would require us to have a definition of "consistency" and that can be challenging, especially across multiple languages. We will continue to explore this, but it will probably not be in the next draft.

**Comment by alastc** [comment]
The response above was approved by the group: https://www.w3.org/2021/04/27-ag-minutes.html#item02
