### ISSUE TITLE
Relation between ACT Rules and methods?

### ISSUE THREAD

**Issue by jpdigital** [w3c/silver#316]
The ACT Rules Community Group has, in my option, done very good work with the available ACT Rules. The indent of methods and the tests for the methods of WCAG 3.0 looks very similar to the ACT Rules. But the description of the tests for methods in the currently available examples is more ambiguous than the description of the exceptions of most ACT Rules. Suggestion: Reuse as much as possible of the work of the ACT Rules Community Group and make sure that the description of the tests for the WCAG is as unambiguous as possible.

**Comment by lauracarlson** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by rachaelbradley** [comment]
Than you for your comment. We worked with ACT to develop guidance for writing new outcomes and methods. We will be using ACT tests whenever possible and working to create similar tests when not.  Please continue to review future drafts and provide feedback through [Github](https://github.com/w3c/wcag3). 

If you disagree with closing this issue, please reopen it in [link to old repo] and add your reasons for reopening it to the comments.
