### ISSUE TITLE
Structured content how-to

### ISSUE THREAD

**Issue by sdw32** [w3c/silver#329]
From the Design section of the Structured content how to:  [https://www.w3.org/WAI/GL/WCAG3/2020/how-tos/structured-content/](url)

> Design the headings in the same font and consistent color scheme with descending font sizes based on the heading level.

A font is a specific set of characters within a typeface. So, for example, Helvetica 12pt bold is a description of a font. Helvetica 14pt semi-bold is a description of a different font. The typeface Helvetica is the family that covers all of these.

So, I think this guideline means to say 'Design the headings in the same typeface'. 
Is this intended to mean the headings should be the same typeface as the body text, or the same typeface as each other?

Using a consistent typeface for all the headings, and a different typeface for the body text can be helpful to make headings visually distinct, and separate from the body text. Changing the size and font-weight are also other useful methods.

**Comment by jpascalides** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by ChrisLoiselle** [comment]
@jspellman This appears to relate more with the heading guideline rather than specifically the visual contrast of text sub group. I'm marking ready for survey as it relates to visual contrast.

**Comment by WilcoFiers** [comment]
Thank you for reviewing and commenting on the WCAG 3 first public working draft. We have an [updated working draft](https://www.w3.org/TR/wcag-3.0/) and the group is starting a new workflow process. To facilitate this transition we have recorded your concern as part of w3c/wcag3#19. You can engage in the discussion around this issue there. 

Please continue to review future drafts and provide feedback through [Github](https://github.com/w3c/wcag3).

If you disagree with closing this issue, please reopen it and add your reasons for reopening it to the comments.
