### ISSUE TITLE
Text Alternatives: Technical Tips

### ISSUE THREAD

**Issue by lbeaze** [w3c/silver#342]
Our products are shipped with SVGs and the guidance doesn't cover them. <title> is the key for an SVG and not an alt attribute. We no longer use image formats supported by IMG because we use the same image assets on all platforms and it would be helpful to be able to send our developers to the technical tips and see something relevant to them.  

Wondering how comprehensive Technical Tips is intended to be.

**Comment by lauracarlson** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by WilcoFiers** [comment]
Thank you for reviewing and commenting on the WCAG 3 first public working draft. We have an [updated working draft](https://www.w3.org/TR/wcag-3.0/) and the group is starting a new workflow process. To facilitate this transition we have recorded your concern as part of w3c/wcag3#20. You can engage in the discussion around this issue there. 

Please continue to review future drafts and provide feedback through [Github](https://github.com/w3c/wcag3).

If you disagree with closing this issue, please reopen it and add your reasons for reopening it to the comments.
