### ISSUE TITLE
Measuring Words question

### ISSUE THREAD

**Issue by paulairy** [w3c/silver#359]
A manual tester evaluates the paragraph, webpage, or section on a rating scale. While we do not know of any mainstream accessibility tool that measures common words, there are some working prototypes of tools developed outside the W3C. We are interested in feedback on testing this guideline and its scoring.

- Is it feasible to test using a readability feature, like the one included with Grammarly?

**Comment by jpascalides** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by jmcsorle** [comment]
Draft Response:
<hr>
From John Rochford: 
"Not yet. The state-of-the-art in readability-testing tools is poor. John Rochford, a member of our team, is developing a better solution. Preliminary work includes analysis of the state-of-the-art (See [Easy COVID-19 Readability Index](https://docs.google.com/document/d/17Znt5GWqIiNzNUs9o6YQQFmbC4U0eVfg6N3azzU38cc/edit?usp=sharing).) and a methodology that operationalizes plain language standards (See [Text Simplification and User Experience](https://link.springer.com/chapter/10.1007/978-3-319-39952-2_28).) We expect this research and development to inform our work."

**Comment by jmcsorle** [comment]
Draft Response:
<hr>
Thank you for your comment. The Clear Words subgroup agrees with John Rochford. The current state of readability tools are not supported by current research. There are new tools being developed that the group is looking into and hope to include in a future draft.   We are not opposed to readability tools per se, but current tools, such as Flesch-Kincaid are not designed to meet the needs we’re targeting.

**Comment by alastc** [comment]
Draft response:

<hr>

Thank you for your comment. This guideline is still in early development, how it is going to be tested is not yet agreed. In general the Clear Words subgroup [agrees with John Rochford.](https://github.com/w3c/silver/issues/359#issuecomment-825205091) The current state of readability tools @@may not be sufficient. There are new tools being developed that the group is looking into and hope to include in a future draft. We are not opposed to using tools, but tools such as Flesch-Kincaid are not designed to meet the needs we’re targeting.
