### ISSUE TITLE
Time for wordsmithing? 

### ISSUE THREAD

**Issue by lbeaze** [w3c/silver#364]
Wondering if this was the time to wordsmith entries or if that is still to come. 

For example, the following bullet list doesn't follow verb / tense pairing to make it more clear. (ironically found on Clear Words). 
- - - 
Design responsibilities

    Ensure that...
        Style the definitions of complex or uncommon words so they are visually prominent
        Design glossary
        If needed, design visually distinct plain language summaries before blocks of text
        Make it easy to find definitions and summaries.
        If possible, use in

**Comment by colabottles** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by jmcsorle** [comment]
Draft Response:
<hr>
Thank you for your suggestion.  The guidelines were included to illustrate the structure rather than to be final guidance on a topic.  We appreciate your feedback and will include it in the next draft.

**Comment by WilcoFiers** [comment]
Thank you for reviewing and commenting on the WCAG 3 first public working draft.  Based on your feedback and that of others, the Accessibility Guidelines Working Group revised the approach to WCAG 3.  You can see the current proposed approach and current status in the [updated working draft](https://www.w3.org/TR/wcag-3.0/).

Please continue to review future drafts and provide feedback through [Github](https://github.com/w3c/wcag3). 

If you disagree with closing this issue, please reopen it in https://github.com/w3c/wcag3/issues and add your reasons for reopening it to the comments.
