### ISSUE TITLE
Feedback on Guideline “Captions” [Deque feedback]

### ISSUE THREAD

**Issue by melaniephilipp** [w3c/silver#378]
The How To document states:  “We want public feedback about whether Open Captions (burned in captions) pass for Bronze level. Open captions are not text and cannot be customized for people with low vision or routed to a braille display for people who are blind-deaf.”

Giving open captions a “1” translates to a Rating of 2 out of 4, which is a fail. Deque believes open captions should pass for Bronze level. 

With respect to routing to a braille display, a complete text transcript that describes not only the auditory aspects of a video but also the visual aspects would not only be more complete, but it can also be consumed at one’s own pace instead of at the pace of a multimedia presentation.

**Comment by colabottles** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by WilcoFiers** [comment]
Thank you for reviewing and commenting on the WCAG 3 first public working draft. We have an [updated working draft](https://www.w3.org/TR/wcag-3.0/) and the group is starting a new workflow process. To facilitate this transition we have recorded your concern as part of w3c/wcag3#23. You can engage in the discussion around this issue there. 

Please continue to review future drafts and provide feedback through [Github](https://github.com/w3c/wcag3).

If you disagree with closing this issue, please reopen it and add your reasons for reopening it to the comments.
