### ISSUE TITLE
Editorial feedback on "Rating for 'Uses visually distinct headings'"

### ISSUE THREAD

**Issue by SDStephens** [w3c/silver#388]
“or less” is used throughout, when it should only be in “0” category

**Comment by jpascalides** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by jspellman** [comment]
Changing assignment to subgroup on Structured Content

**Comment by jenstrickland** [comment]
Draft Response:

The structured content sub-group agrees will include them in our work. Thank you for your insightful comments!

**Comment by cwadamsoforacle** [comment]
Based on comments from the FPWD we have decided to explore alternate approaches to testing and scoring. We appreciate your feedback and are closing this issue based on the changes to approach.
