### ISSUE TITLE
Adobe Comments on Text alternative available

### ISSUE THREAD

**Issue by awkawk** [w3c/silver#402]
It seems that it hasn’t been decided whether this includes all non-text content (e.g. audio) or just visual information. If audio is included, why isn’t “sensory – auditory” included in the functional categories?

Also, why is the rating scale skewed to disfavor Rating 4?

Counting the number of images on pages/views is harder than it seems. No tools currently support this.

**Comment by jpascalides** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by WilcoFiers** [comment]
Thank you for reviewing and commenting on the WCAG 3 first public working draft. We have an [updated working draft](https://www.w3.org/TR/wcag-3.0/) and the group is starting a new workflow process. To facilitate this transition we have recorded your concern as part of w3c/wcag3#20. You can engage in the discussion around this issue there. 

Please continue to review future drafts and provide feedback through [Github](https://github.com/w3c/wcag3).

If you disagree with closing this issue, please reopen it and add your reasons for reopening it to the comments.
