### ISSUE TITLE
Adobe Comments on Captions

### ISSUE THREAD

**Issue by awkawk** [w3c/silver#404]
Question about whether open captions should be the same as closed captions – we believe that the goal is to support the different functional requirements and captions that are “burned in” to the video stream as part of the video data rather than as information that is presented as an overlay only support users at a basic level. Therefore, a lower rating could be applied to open captioned content.

**Comment by jpascalides** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by WilcoFiers** [comment]
Thank you for reviewing and commenting on the WCAG 3 first public working draft. We have an [updated working draft](https://www.w3.org/TR/wcag-3.0/) and the group is starting a new workflow process. To facilitate this transition we have recorded your concern as part of w3c/wcag3#23. You can engage in the discussion around this issue there. 

Please continue to review future drafts and provide feedback through [Github](https://github.com/w3c/wcag3).

If you disagree with closing this issue, please reopen it and add your reasons for reopening it to the comments.
