### ISSUE TITLE
Email: WCAG3 public comment (Captions Scoring)

### ISSUE THREAD

**Issue by jspellman** [w3c/silver#421]
[Comment from Email](https://lists.w3.org/Archives/Public/public-agwg-comments/2021Feb/0007.html):

Hi

I like the idea of scoring, however I am wondering if you will address accuracy of content anywhere?

For example in the Method: Provides text equivalents of speech and non-speech there are three ratings:
0 - no captions
1 - open captions
2 - closed captions

How would you score a video with captions that were inaccurate (such as automatic captioning on YouTube)? Or score a video that captioned the text but missed out on important non-speech audio? Or score a video that had spelling mistakes? All these videos are various levels of accessibility compliance and can’t be given a score of 0, 1 or 2.

Thanks
Gian

**Comment by jspellman** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by WilcoFiers** [comment]
Thank you for reviewing and commenting on the WCAG 3 first public working draft. We have an [updated working draft](https://www.w3.org/TR/wcag-3.0/) and the group is starting a new workflow process. To facilitate this transition we have recorded your concern as part of w3c/wcag3#23. You can engage in the discussion around this issue there. 

Please continue to review future drafts and provide feedback through [Github](https://github.com/w3c/wcag3).

If you disagree with closing this issue, please reopen it and add your reasons for reopening it to the comments.
