### ISSUE TITLE
Email: WCAG 3.0 public comment (4 - How-Tos with video and illustrations)

### ISSUE THREAD

**Issue by jspellman** [w3c/silver#427]
[Comment from Email](https://lists.w3.org/Archives/Public/public-agwg-comments/2021Feb/0010.html): 
from [spreadsheet](https://lists.w3.org/Archives/Public/public-agwg-comments/2021Feb/att-0010/20210226drempelvrij_Foundation_-_comments_on_working_drafts_WCAG_3.0.xlsx)

The core   guidelines are understandable by a non-technical audience. Text and   presentation are usable and understandable through the use of plain language,   structure, and design . 

Including   instruction videos and illustrated how-to’s.

**Comment by jspellman** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by jspellman** [comment]
Draft Response: We are rewording based on your comment.  We will change the Requirement 4.5 Readibility to say: "The core guidelines are understandable by a non-technical audience. Text and presentation are usable and understandable through the use of plain language, structure, and design. They link to instruction videos, illustrations and how-to where available. Creation of new videos and illustrations are outside the scope of this project at this time."

**Comment by alastc** [comment]
CLosed as done.

**Comment by alastc** [comment]
Someone needs to respond to the email: https://lists.w3.org/Archives/Public/public-agwg-comments/2021Feb/0010.html
