### ISSUE TITLE
Email: ITI Comments on First Public Working Draft of W3C Accessibility Guidelines (WCAG) 3.0 (16 - Types of tests)

### ISSUE THREAD

**Issue by jspellman** [w3c/silver#458]
[Comment from Email](https://lists.w3.org/Archives/Public/public-agwg-comments/2021Feb/0012.html): 
from [PDF](https://lists.w3.org/Archives/Public/public-agwg-comments/2021Feb/att-0012/ITI_Comments_on_WCAG_3.0_First_Public_Working_Draft_20210224_1_.pdf)

2.	5.3 Types of tests: We are looking for more appropriate terms to distinguish between these two types of tests and welcome suggestions.

ITI agrees that the names for the two types of tests referenced in 5.3 are likely to cause confusion. In particular, “Atomic testing” appears to be in conflict with the definition as used by the ACT Task Force. One possible suggestion for replacement would be to replace "atomic testing" and "holistic testing" with "Module testing" and "end-to-end testing", respectively.

**Comment by jspellman** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by cwadamsoforacle** [comment]
Draft Response:

Thank you for your comment.  This terminology is intended to express concepts that have yet to be fully explored.  The working group will maintain a list of different possible terms for these concepts, which will guide us as we explore these concepts in greater detail.

**Comment by alastc** [comment]
Suggest adding at the end of the response: "Your suggestions will be included as proposals for those concepts, and we'll tag this issue to come back to at an appropriate point later."
