### ISSUE TITLE
The "licence", "contributing" and "code of conduct" documents 404

### ISSUE THREAD

**Issue by hollsk** [w3c/silver#46]
The [README.md](https://github.com/w3c/silver/blob/master/README.md) contains this sentence:

>Contributors to this repository should read the License, Contributing, and Code of Conduct pages. 

The documents linked to don't exist in this repository. Do the documents exist somewhere else instead?

**Comment by jspellman** [comment]
Emailed @michael-n-cooper to fix. That's W3C required info, I believe.

**Comment by michael-n-cooper** [comment]
This hadn't been set up because of uncertainty whether this repository should be attached to the Community Group or the Task Force, which have difference license requirements. After discussion with the facilitators, we opted for the Community Group and the appropriate files are now in place.
