### ISSUE TITLE
Requirements comment from Leonie Watson

### ISSUE THREAD

**Issue by jspellman** [w3c/silver#5]
From email from Leonie Watson: https://lists.w3.org/Archives/Public/public-silver/2018May/0050.html 
The requirements document is clear and easy to read (a good match for 
the design principles it describes).

I'd be tempted to reorder the content. Describing the principles before 
the problem space seems counter-intuitive to me. Describing the problem 
space, and then describing the proposed solution/design principles, 
feels like a better narrative to me.

The language of the document focuses on people with disabilities in the 
conventional/permanent sense (likely a legacy of the language used in 
WCAG). I think this exclusive definition is too narrow for the next 
generation of accessibility guidelines though, and suggest we 
acknowledge that disability can be permanent, temporary, or situational, 
and that any/all of these is relevant to accessibility in the UI.

I wonder if the document is misnamed? This is one of those philosophical 
things that could put us in the bikeshed for all eternity, but I'll 
suggest that it should be renamed "Design principles" instead.

Good work on this though. It's so good to see it starting to take shape.

**Comment by mikecrabb** [comment]
consensus to reorder and add a definition in the introduction
