### ISSUE TITLE
Revise Creation Process to conduct research and studies

### ISSUE THREAD

**Issue by rachaelbradley** [w3c/silver#587]
This issue is the 2nd part of [Issue 227](https://github.com/w3c/silver/issues/227)

And under Creation Process:

Pro-actively conduct research and studies with a cross section of all users to validate the usefulness and effect of guidelines, methods, and practices. Recruiting a diverse range of people to include not only those the guideline is intended to help, but also a group recruited from all users to fully understand the helpful impact and utility of the method or guideline. This recognizes the importance of user contributions toward advancing these standards, as well as improving the protection and inclusivity of accessibility tooling and procedures.

**Comment by Myndex** [comment]
Hi Rachael,

Just to mention, related to this subject is the potential need for setting up some form of an **institutional review board** to provide at least basic oversight of studies. While I don't think that the kinds of studies envisioned here would *require* registration at clinicalTrials.gov, many journals do require that human studies, even observational (non-intervention), must register at clinicalTrials.gov before enrolling participants, i**n order to published the results.** And clinicalTrials.gov implies that such studies need approval from the institutional review board.

[Here's a checklist form,](https://prsinfo.clinicaltrials.gov/ACT_Checklist.pdf) regarding if one must register.

> ### _Human Subjects Review_ 
> **Definition:** _Studies must have approval (or be exempt, as appropriate) from a Human Subjects Protection Review Board prior to the enrollment of the first participant to be eligible for registration. A study may be submitted for registration prior to approval by the review board so long as the study is not yet recruiting participants._ 

At a minimum, appropriate informed consent needs to be part of the process. For  simple observational studies that are non-interventional, the needed ICF is probably simple, such as the [one I wrote for PercepTex].(https://www.myndex.com/perceptex/MMU/index/JoinStudy).


## APPENDIX:
### [_clinicalTrials.gov_](https://clinicaltrials.gov/ct2/manage-recs/how-register#StepsForRegistering)
The US NIH clearing house for registering clinical studies and trials.

## GLOSSARY
### _Clinical study_
_A research study involving human volunteers (also called participants) that is intended to add to medical knowledge. There are two types of clinical studies: interventional studies (also called clinical trials) and observational studies._

### _Human subjects protection review board_
_A group of people who review, approve, and monitor the clinical study's protocol. Their role is to protect the rights and welfare of people participating in a study (referred to as human research subjects), such as reviewing the informed consent form. The group typically includes people with varying backgrounds, including a community member, to make sure that research activities conducted by an organization are completely and adequately reviewed.
**Also called an institutional review board, or IRB, or an ethics committee**._

### _Observational study_
_A type of clinical study in which participants are identified as belonging to study groups and are assessed for biomedical or health outcomes. Participants are **not assigned** to a specific intervention/treatment. A patient registry is a type of observational study._

### _Observational study model_
_The general design of the strategy for identifying and following up with participants during an observational study. Types of observational study models include cohort, case-control, case-only, case-cross-over, ecologic or community studies, family-based, and other._

**Comment by alastc** [comment]
Proposed response: 
<hr>

Our general process is to start from the available research and form guidelines from that. There are occasions where additional research is needed, but this is not the default process, and would not be added as a requirement or statement of standard practice.
