### ISSUE TITLE
WCAG 3.0 Review: WCAG 3.0 scope of technologies

### ISSUE THREAD

**Issue by maryjom** [w3c/silver#611]
It seems that the scope of the standard conflicts between different sections. Maybe I'm misreading. I realize there's some push and pull to either keep WCAG 3 focused on web-only vs. WCAG's known use and application outside of web technologies. The abstract’s stated scope of the standard says “These guidelines address accessibility of web content on desktops, laptops, tablets, mobile devices…” However, in section 1.3 Goals and Requirements, it says the goal is to make digital products including web, ePub, PDF, applications, mobile apps and other emerging technologies…” The introduction also says “Following these guidelines will make content more accessible…” This leaves the question, is WCAG 3 covering native applications and mobile applications as well as web-based content?  If this is only covering web-based content (no matter what technology it is rendered on) it should say so. Will we need to have an updated WCAG2ICT Note to show how the guidelines might be applied to various non-web technologies or will those considerations be included in the guidelines, outcomes, and methods created for WCAG 3?

**Comment by bbrown0** [comment]
WCAG 3.0 does not provide normative guidance on non-web technologies; however, informational guidance my include examples outside the scope of the web.

**Comment by gundulaniemann** [comment]
I feel the response contradicts what was discussed last week with https://docs.google.com/document/d/1tpgJaoIHC4IywvFkfXrfa8mEcSlEtAP-P0_46vNqynY/edit#heading=h.vc6kiqsxgozk
Herein, effort has been made to keep the normative part technology agnostic and to put technology dependencies in the methods only, but not in the outcomes.

**Comment by rachaelbradley** [comment]
**Suggested alternative response:** WCAG 3.0's charter does not provide normative guidance on non-web technologies; however, we are exploring writing the normative guidance to be technology agnostic and informational guidance within WCAG 3 or supplemental notes such as WCAG2ICT may include examples outside the scope of the web.

**Comment by gundulaniemann** [comment]
> **Suggested alternative response:** WCAG 3.0's charter does not provide normative guidance on non-web technologies; however, we are exploring writing the normative guidance to be technology agnostic and informational guidance within WCAG 3 or supplemental notes such as WCAG2ICT may include examples outside the scope of the web.

Thank you for the extra explanation. I like the response.
