### ISSUE TITLE
"Image accessible name is descriptive" is a bad title

### ISSUE THREAD

**Issue by johnfoliot** [w3c/silver#687]
Re: https://www.w3.org/WAI/standards-guidelines/act/rules/qt1vmo/proposed/

EDITORIAL PROPOSAL: Change the title to **Image accessible name is a functional equivalent**
<hr />
This document is currently titled Image accessible name is descriptive, which is already off to a bad start: image alternative text(s) are intended to be a functional equivalent to the image (aka accessible NAME), and not just a "description" (aka accessible DESCRIPTION). 

For example, when you see the following code pattern:

  `<a href="foo.html">` `<img src="printer_icon.png">` `</a>`

...the alternative text is not (or rather should not be) "black and white printer icon" (which is a literal description of the image), but instead "Print" (or better, "Print this page"), because that is the **functional intent of that image.** 

The current draft also shows the following:

```
<html lang="en">
	<img src="/test-assets/shared/w3c-logo.png" alt="W3C logo" />
</html>
```

Which isn't always wrong, but would certainly be wrong if used like this:

```
<html lang="en">
	<a href="https://w3.org"><img src="/test-assets/shared/w3c-logo.png" alt="W3C logo" /></a>
</html>
```

...because the link does not take the user to "W3C logo" (a thing, but not a destination). In that case the text alternative example should be:

```
<html lang="en">
	<a href="https://w3.org"><img src="/test-assets/shared/w3c-logo.png" alt="W3C Home" /></a> (or similar)
</html>
```

Likewise, this would also be wrong:

Incorrect:
`<img src="piechart.png" alt="A circular pie chart with 12 sections, each section is a different color and labeled January, February, March, April, May, etc." />`    [that is, per the document, a "description" of the image]

Correct:
`<img src="piechart.png" alt="Fiscal earnings for calendar 2022" />`  [accessible NAME]
```
<details> 
  <summary> Chart Data</summary>  [accessible DESCRIPTION]
  <p>The chart shows monthly earnings for each of the 12 months:</p>
  <ul>
    <li>January: $22,000</li>
    <li>February: $18,700</li>
    <li>March: $24,100</li>
    ...
  </ul>
</details>
```
As such, much of the content on that resource page that states "...describes the image" (or a variant of that) is incorrect: it's NOT a description, it's a **text string that serves the equivalent function of the image** (i.e., an alternative) and provides an accessible name to the image.

**Comment by WilcoFiers** [comment]
@johnfoliot I've copied this issue to the ACT Rules repository, which is where the source of this lives. We'll pick up the work there.
