### ISSUE TITLE
Functional needs for alternative content for audio and video

### ISSUE THREAD

**Issue by slauriat** [w3c/silver#69]
Draft functional needs for [SC 1.2.1 Audio-only and Video-only (Prerecorded), SC 1.2.8 Media Alternative (Prerecorded), SC 1.2.9 Audio-only (Live)](https://docs.google.com/document/d/1aCRXrtmnSSTso-6S_IO9GQ3AKTB4FYt9k92eT_1PWX4/edit#heading=h.wybvadozdbds)

**Comment by hallmedia** [comment]
**Complete**.

**Process**:
Copy and paste the ‘Benefits’ bullets (or ‘Intent’ statement when no Benefits provided) from each Understanding Doc; then edit the copy to convert disability-first or person-first language into functional needs. Then, add any functional needs that may be unique to the grouping of SC or any that may have been missed in the Understanding Docs.

**Example**:
Original benefit of 1.2.1: “Usage without vision and without hearing. People who are deaf-blind can read the text in braille.”
Edited functional need: “Usage without vision and without hearing.”

**Comment by hallmedia** [comment]
- [ ] Assigned: Charles Hall
- [ ] Meeting or Work started
- [ ] Draft Completed
- [ ] Reviewed by Silver group

**Comment by hallmedia** [comment]
**Complete**.

**Process**:
Copy and paste the ‘Benefits’ bullets (or ‘Intent’ statement when no Benefits provided) from each Understanding Doc; then edit the copy to convert disability-first or person-first language into functional needs. Then, add any functional needs that may be unique to the grouping of SC or any that may have been missed in the Understanding Docs.

**Example**:
Original benefit of 1.2.1: “Usage without vision and without hearing. People who are deaf-blind can read the text in braille.”
Edited functional need: “Usage without vision and without hearing.”

**Comment by slauriat** [comment]
Reviewed and finalized draft.
