### ISSUE TITLE
Test issue - Too much contrast

### ISSUE THREAD

**Issue by alastc** [w3c/silver#705]
An issue for testing, it will be deleted later. Look away, there is nothing to see here.

For this hypothetical issue, pasting in a current one:
"Anbased color contrast guideline looks like a great improvement over existing guidelines. However, sufficient contrast alone does not guarantee accessible colors. I worry that the the recommendations for dark themes may incentivize the adoption of palettes with different accessibility issues."

**Comment by rachaelbradley** [comment]
I think A need to B.

**Comment by alastc** [comment]
Comment from someone who agrees with the issue, there should be a max contrast level.

**Comment by cwadamsoforacle** [comment]
> Comment from someone who agrees with the issue, there should be a max contrast level.

Disagree with max, we should focus on min first.

**Comment by rachaelbradley** [comment]
@alastc I also agree but there should also be a min.
