### ISSUE TITLE
Regulatory Environment - 4.6 unclear

### ISSUE THREAD

**Issue by iadawn** [w3c/silver#727]
Relates to:

> 4.6 Regulatory Environment
>
> The Guidelines provide broad support, including
>
> * Structure, methodology, and content that facilitates adoption into law, regulation, or policy, and
> * clear intent and transparency as to purpose and goals, to assist when there are questions or controversy.

The purpose and framing of this requirement is unclear. It is also difficult to see what is required to make the guidelines 'regulator ready'.

Recommendation:

Ideally, remove this requirement. I am not clear on what it adds.

If there is a desire to keep it then better articulate what the requirement is. This may need some of the following:

* Better explain 'provide broad support'. It is unclear what 'broad support' actually relates to, covers or means.
* Clarify what structure, methodology and content requirements would facilitate adoption
* Move 'clear intent...' to it's own requirement - something like 'All Guidelines should include supporting commentary on intent and transparency as to purpose and goals'

**Comment by GreggVan** [comment]
Agree that it is hard to understand.   But what it is trying to convey is critical to adoption by regulatory agencies and adoption by regulatory agencies has been shown as critical to widespread adoption in practice - which is one of the main contribution of WCAG in advancing accessibility.

To make it easier to understand -- we have reformulated it as follows.

4.6 Regulatory Environment
WCAG 3 requirements written such that structure, methodology, and content facilitates adoption into law, regulation, or policy, to encourage adoption in practice by making their need clear and a clear and objective definition of when requirements are met.

**Comment by alastc** [comment]
There has been a lot of discussion around testability and true/false statements. Different people have different thoughts on what 'objective' means. 

Suggest: "a clear definition of when requirements are met"
