### ISSUE TITLE
4.7 Motivation

### ISSUE THREAD

**Issue by iadawn** [w3c/silver#728]
Relates to:

>  4.7 Motivation
> 
> The Guidelines motivate organizations to go beyond minimal accessibility requirements by providing a scoring system that rewards organizations which demonstrate a greater effort to improve accessibility.

It is unclear what evidence there is to support this as a requirement. WCAG 2.2, arguably, provides a scoring system that encourages organisations to go beyond the minimally required accessibility requirements: how many SCs at AAA pass. Yet there is nothing that would suggest this acts as a motivational feature.

Scoring that is a valid reflection of a sites accessibility, reliable and stable in assessment is useful. However, couching it as a motivational requirement does not make sense.

**Comment by nitedog** [comment]
Relates to #655

**Comment by nitedog** [comment]
Draft response:

> Many thanks for your comment. The phrase "scoring system" in this sentence was changed to "conformance model", to not limit ourselves to one particular approach. This might partially address your concern. Another aspect is that the WCAG 2.x levels could be too coarse to achieve a motivational effect, which is something we can learn from.

**Comment by alastc** [comment]
@iadawn can we close this one? There is an update elsewhere, and we will adjust wording in [issue 44](https://github.com/w3c/wcag3/issues/44#issuecomment-1966686301).

I'll close for now, and I'll highlight when the wording for this requirement comes up again.
