### ISSUE TITLE
4.8 Scope

### ISSUE THREAD

**Issue by iadawn** [w3c/silver#729]
Relates to:

> 4.8 Scope
>
> The guidelines provide guidance for people and organizations that produce digital assets and technology of varying size and complexity. This includes large, dynamic, and complex websites. Our intent is to provide guidance for a diverse group of stakeholders including content creators, browsers, authoring tools, assistive technologies, and more.

This is possibly poorly named, since 'Scope' isn't really a requirement. However, more broadly this sort of guidance does not belong in the standard but in supporting material. This may be a broader requirement of the W3C/WAI community rather than a specific requirement of the Guidelines.

**Comment by nitedog** [comment]
> This is possibly poorly named, since 'Scope' isn't really a requirement.

Will be addressed through issue #44, to evaluate whether all requirements from WCAG 3 are testable.

> However, more broadly this sort of guidance does not belong in the standard but in supporting material.

Is addressed through the revised text proposed for issue #224: "_The guidelines provide guidance and a conformance model for people and organizations that produce digital assets and technology of varying size and complexity. This includes large, dynamic, and complex websites. The associated informative materials will include guidance for a diverse group of stakeholders including content creators, browsers, authoring tools, assistive technologies, and more._"

> This may be a broader requirement of the W3C/WAI community rather than a specific requirement of the Guidelines.

Core level guidance needs to be part of the WCAG 3 package, regardless which W3C/WAI group it comes from. Removing this part could result in this not being addressed.

**Comment by alastc** [comment]
TF happy with the response. AC needs to do a PR for #224 to implement the suggestion.

**Comment by alastc** [comment]
This has been updated, and will be reviewed again in #735
