### ISSUE TITLE
Make gh-pages a default branch or auto-build it on commits

### ISSUE THREAD

**Issue by chaals** [w3c/silver#8]
The gh-pages barnch is a special one that github provides so it is possible to read things easily and efficiently. In this repo it is out of synch with the master branch,, which is the default.

It could be auto-synched, or we could use e.g. respec and generate content from commits on master that are put into the gh-pages branch, or we can just make gh-pages the deafult on the basis that for now we are not going to have anything that gets built after committing.

But we should somehow make this simpler to use.

**Comment by mikecrabb** [comment]
Seems to have been actioned. Closing issue.
